name: dhall-resolve
description: Build and package Dhall sources as one file
author: Nikita Volkov
branding:
  color: blue
inputs:
  file:
    description: Path to source file
    required: true
  cse:
    description: Apply common subexpression elimination to reduce output size
    required: false
    default: 'false'
outputs:
  path:
    description: Path to the generated file
runs:
  using: docker
  image: docker://ghcr.io/nikita-volkov/dhall-resolve.github-action:35d7a928f5650d4b08bfbbe9d4edbfbf3e6aa889
  env:
    file: ${{ inputs.file }}
    cse: ${{ inputs.cse }}
