name: dhall-resolve
description: Build and package Dhall sources as one file
author: Nikita Volkov
branding:
  color: blue
inputs:
  file:
    description: Path to source file
    required: true
outputs:
  path:
    description: Path to the generated file
runs:
  using: docker
  image: docker://ghcr.io/nikita-volkov/dhall-resolve.github-action:b678e0dc99cd29e6c5acdb5265af3d68d48f1cc0
  env:
    file: ${{ inputs.file }}
