name: dhall-resolve
description: Build and package Dhall sources as one file
author: Nikita Volkov
branding:
  color: blue
inputs:
  file:
    description: Path to source file
    required: true
  minify:
    description: Minify the output through CSE and DCE
    required: false
    default: 'false'
outputs:
  path:
    description: Path to the generated file
runs:
  using: docker
  image: docker://ghcr.io/nikita-volkov/dhall-resolve.github-action:4ae18b7efdedab84338d2d086452fd3c8eb148dc
  env:
    file: ${{ inputs.file }}
    minify: ${{ inputs.minify }}
